from .Property import FilteredProperty, IProperty, IProperty_r, Property


class IFlag_r(IProperty_r[bool]): ...

class IFlag(IProperty[bool]): ...

class Flag(Property[bool], IFlag): ...

class FilteredFlag(FilteredProperty[bool], IFlag): ...
