from .Property import FilteredProperty, IProperty, IProperty_r, Property


class IText_r(IProperty_r[str]):
    ...

class IText(IProperty[str]):
    ...

class Text(Property[str], IText): ...

class FilteredText(FilteredProperty[str], IText): ...

# class TextState(FilteredProperty[str|None]): ...

